---
- hosts: appservers
  become: yes

  vars:
    version: "{{ version }}"
    tomcat_version: "9.0.89"
    tomcat_install_dir: "/opt/tomcat"

  tasks:

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Create tomcat user
      user:
        name: tomcat
        home: "{{ tomcat_install_dir }}"
        shell: /bin/false

    - name: Create Tomcat directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: tomcat
        group: tomcat

    - name: Download Tomcat archive
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat.tar.gz"

    - name: Extract Tomcat archive
      unarchive:
        src: "/tmp/apache-tomcat.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Ensure Tomcat scripts are executable
      file:
        path: "{{ tomcat_install_dir }}/bin"
        mode: "0755"
        recurse: yes

    - name: Set Tomcat permissions
      file:
        path: "{{ tomcat_install_dir }}"
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Deploy WAR file
      get_url:
        url: "http://172.21.2.161:8081/repository/vprofile-release/QA/vproapp/{{ version }}/vproapp-{{ version }}.war"
        dest: "{{ tomcat_install_dir }}/webapps/vprofile.war"
        mode: '0644'

    - name: Install Tomcat service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat 9
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment=JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          Environment=CATALINA_HOME={{ tomcat_install_dir }}
          Environment=CATALINA_BASE={{ tomcat_install_dir }}

          ExecStart={{ tomcat_install_dir }}/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/bin/shutdown.sh

          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart Tomcat service
      systemd:
        name: tomcat
        state: restarted
        enabled: yes
